name: MineShaft
main: p2e\mineshaft\MineShaft
version: 0.0.3
api: 4.0.0
author: P2E

permissions:
  mineshaft.tp:
    description: "Ability to use /mine"
    default: true

commands: 
  mine: 
    description: "Teleport to a mine"
    usage: /mine [MineName]
    permission: "mineshaft.tp"