# Set this option to true if you want MineShaft to protect the ores of each mine.

protection:
  enabled: true
  entire_world: false

refill:
  automatic: true
  type: percent
  percentage: 10
  interval: 600

use_server_spawn: true;
